name: Fullstack CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: node:18  # Use a Node.js Docker container

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # ========== FRONTEND ==========
      - name: Install Frontend dependencies
        working-directory: ./front
        run: npm install

      - name: Build Frontend
        working-directory: ./front
        run: npm run build

      - name: Run Frontend Unit Tests
        working-directory: ./front
        run: npm test -- --watchAll=false

      # ========== BACKEND ==========
      - name: Install Backend dependencies
        working-directory: ./back
        run: npm install
        
      # ========== AUTOMATION TESTS ==========
      - name: Install Playwright dependencies
        working-directory: ./AutomationTest
        run: npm install

      - name: Install Playwright Browsers
        working-directory: ./AutomationTest
        run: npx playwright install

      - name: Run Playwright Tests
        working-directory: ./AutomationTest
        run: npm run test  # or your specific Playwright command
